title: Gaeun's Future Resume
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Lee Gaeun"
job: "〈student〉"

phone_number: 010-4805-7385
address: Seoul in Korea
email: lucxeun0109@gmail.com
linkedin_username: Non
github_username: rkdms0109
instagram_username: _lucxeun_05
twitter_username: None
facebook_username: None
youtube_username: None
blog_url: https://blog.naver.com/eun_01_09/223373288831

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag